version: '3'
services:
  uwazi-main:
    build:
      context: .
      dockerfile: uwazi.Dockerfile
    container_name: uwazi-main
    volumes:
      - .:/usr/src/app
    ports:
      - '80:80'
    command: NODE_ENV=production yarn blank-state DatabaseName
    environment:
      - NODE_ENV=production 
      - DATABASE_NAME=DatabaseName 
      - INDEX_NAME=DatabaseName 
      - FILES_ROOT_PATH=/usr/src/app/uwazi/
    entrypoint: [ "node", "server.js" ]