#!/bin/bash

set -eo pipefail

function start {
  mkdir -p uwazi/log uwazi/uploaded_documents uwazi/custom_uploads uwazi/temporal_files
  if [ ! -f uwazi/uwazi.tgz ]
  then
    wget -O uwazi/uwazi.tgz https://github.com/huridocs/uwazi/releases/latest/download/uwazi.tgz
    cd uwazi
    tar xvf uwazi.tgz
    mv prod latest
    cd ..
  fi
  docker-compose up --build -d "${@}"
}

function mongo {
  docker exec -it uwazi-mongo mongo localhost/uwazi_development
}

function stop {
  docker-compose stop
}


function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
